---
title: "simulation 결과"
author: "Seo Jae Hyun"
date: '2022-10-31'
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(gridExtra)
```


```{r data importing}

type_binomial_trial100 = read.csv('100_type_binomial_trial_250.csv')
type_poisson_trial100 = read.csv('100_type_poisson_trial_250.csv')
type_ZIP_trial100 = read.csv('100_type_ZIP_trial_250.csv')
type_binomial_trial300 = read.csv('300_type_binomial_trial_250.csv')
type_poisson_trial300 = read.csv('300_type_poisson_trial_250.csv')
type_ZIP_trial300 = read.csv('300_type_ZIP_trial_250.csv')
type_binomial_trial500 = read.csv('500_type_binomial_trial_250.csv')
type_poisson_trial500 = read.csv('500_type_poisson_trial_250.csv')
type_ZIP_trial500 = read.csv('500_type_ZIP_trial_250.csv')
type_ZIP_trial1000 = read.csv('1000_type_ZIP_trial_250.csv')
type_binomial_trial1000 = read.csv('1000_type_binomial_trial_250.csv')
type_poisson_trial1000 = read.csv('1000_type_poisson_trial_250.csv')
type_binomial_trial3000 = read.csv('3000_type_binomial_trial_250.csv')
type_poisson_trial3000 = read.csv('3000_type_poisson_trial_250.csv')


```


```{r result interpretation}



make_result = function(dataframe, truevalue, sample){
  
  
  mse_local = round(mean((dataframe$zipest-truevalue)^2), 3)
  mse_lin = round(mean((dataframe$linest-truevalue)^2), 3)
  
  abs_local = round(mean(abs(dataframe$zipest-truevalue)/truevalue), 3)
  abs_lin = round(mean(abs(dataframe$linest - truevalue)/truevalue), 3)
  
  ci_local = round(mean(dataframe$zip_ci_left <= truevalue & dataframe$zip_ci_right >= truevalue, na.rm=T), 3)
  ci_lin = round(mean(dataframe$lin_ci_left <= truevalue & dataframe$lin_ci_right >= truevalue, na.rm=T), 3)
  
  result = data.frame('num_sam' = sample, 'mselocal' = mse_local, 'abslocal' = c(abs_local), 'cilocal' = c(ci_local), 'mselin' = mse_lin, 'abslin' = abs_lin, 'cilin' = ci_lin)
  
  return(result)
}

```


``` {r binomial case}

#n = 100
logistic = function(x) { exp(x)/(1+exp(x))}

truediff_binomial =logistic(-0.3) - logistic(1.5)


bin100 = make_result(type_binomial_trial100, truediff_binomial, 100)



#n = 300


bin300 = make_result(type_binomial_trial300, truediff_binomial, 300)




#n = 500

bin500 = make_result(type_binomial_trial500, truediff_binomial, 500)


#n = 1000

bin1000 = make_result(type_binomial_trial1000 %>% .[2:202, ], truediff_binomial, 1000)

#n = 3000

bin3000 = make_result(type_binomial_trial3000, truediff_binomial, 3000)


binomial = rbind(bin100, bin300, bin500, bin1000, bin3000)


colnames(binomial) = c('N', 'local likelihood mse', 'local likelihood arb', 'local likelihood coverage', 'local linear mse', 'local linear arb', 'local linear coverage')



```




```{r poisson case}





truediff_poisson = exp(2.3) - exp(1.1)

poi100 = make_result(type_poisson_trial100, truediff_poisson, sample=100) 

poi300 = make_result(type_poisson_trial300, truediff_poisson, sample=300) 

poi500 = make_result(type_poisson_trial500, truediff_poisson, sample=500)

poi1000 = make_result(type_poisson_trial1000, truediff_poisson, sample=1000)

poi3000 = make_result(type_poisson_trial3000, truediff_poisson, sample=3000)


poi = rbind(poi100, poi300, poi500, poi1000, poi3000)



colnames(poi) =  c('N', 'local likelihood mse', 'local likelihood arb', 'local likelihood coverage', 'local linear mse', 'local linear arb', 'local linear coverage')



```


```{r zip case}


truediff_zip = exp(2.3)/(1+exp(-0.3)) - exp(1.1)/(1+exp(1.5))

zip100 = make_result(type_ZIP_trial100 %>% filter(zipest>-10^2, linest>-10^2), truediff_zip, 100)

zip300 = make_result(type_ZIP_trial300 %>% filter(zipest>-10^2, linest>-10^2), truediff_zip, 300)

zip500 = make_result(type_ZIP_trial500, truediff_zip, 500)

zip1000 = make_result(type_ZIP_trial1000, truediff_zip, 1000)

zip = rbind(zip100, zip300, zip500, zip1000)
  


colnames(zip) = c('N', 'local likelihood mse', 'local likelihood arb', 'local likelihood coverage', 'local linear mse', 'local linear arb', 'local linear coverage')

```



```{r dataframe save}

write.csv(binomial, 'binomial.csv')
write.csv(poi, 'poi.csv')
write.csv(zip, 'zip.csv')


```


```{r visualization}


# final file : concatnating binomial.csv, poi.csv and zip.csv files

final = read.csv('final.csv')





make_graph = function(data, type1){
  
  
  mse = data %>% filter(type == type1) %>%  ggplot() + geom_line(mapping = aes(x=factor(N), y= mse, color=model, group=model), size=3) +
    geom_point(mapping = aes(x = factor(N), y=mse, color=model, group=model), size=6) +theme_bw()+
  theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), 
        panel.grid.major.y = element_blank(), panel.grid.minor.y = element_blank(), 
        #axis.ticks.x=element_blank(), 
        #axis.ticks.y=element_blank(), 
        axis.text.y=element_text(size=15), 
        axis.text.x=element_text(size=15),
        axis.title.x = element_text(size=20),
        axis.title.y = element_text(size=20),
        plot.title = element_text(face = "bold", size = 15, hjust = 0.5),
        legend.title = element_blank(), legend.text = element_text(size=30), legend.position='bottom') + scale_color_manual(values= c('red','blue'))+ xlab('Sample size') + ylab('MSE')
  
  arb = data %>% filter(type == type1) %>%  ggplot() + geom_line(mapping = aes(x=factor(N), y= arb, color=model, group=model), size=3) +
    geom_point(mapping = aes(x = factor(N), y=arb, color=model, group=model), size=6) +theme_bw()+
  theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), 
        panel.grid.major.y = element_blank(), panel.grid.minor.y = element_blank(), 
        #axis.ticks.x=element_blank(), 
        #axis.ticks.y=element_blank(), 
        axis.text.y=element_text(size=15), 
        axis.text.x=element_text(size=15),
        axis.title.x = element_text(size=20),
        axis.title.y = element_text(size=20),
        plot.title = element_text(face = "bold", size = 15, hjust = 0.5),
        legend.title = element_blank(), legend.text = element_text(size=30), legend.position='bottom') + scale_color_manual(values= c('red','blue'))+ xlab('Sample size') + ylab('ARB')
  
  coverage = data %>% filter(type == type1) %>%  ggplot() + geom_line(mapping = aes(x=factor(N), y= coverage, color=model, group=model), size=3) +
    geom_point(mapping = aes(x = factor(N), y=coverage, color=model, group=model), size=6) +theme_bw()+
  theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), 
        panel.grid.major.y = element_blank(), panel.grid.minor.y = element_blank(), 
        #axis.ticks.x=element_blank(), 
        #axis.ticks.y=element_blank(), 
        axis.text.y=element_text(size=15), 
        axis.text.x=element_text(size=15),
        axis.title.x = element_text(size=20),
        axis.title.y = element_text(size=20),
        plot.title = element_text(face = "bold", size = 15, hjust = 0.5),
        legend.title = element_blank(), legend.text = element_text(size=30), legend.position='bottom') + ylim(0, 1) +  scale_color_manual(values= c('red','blue')) + geom_hline(yintercept=0.95, linetype=2) + xlab('Sample size') + ylab('Coverage')
  
  
  return(list(mse, arb, coverage))
  
}


bernoulli_graph = make_graph(final, 'bernoulli')

poi_graph = make_graph(final, 'poi')

zip_graph = make_graph(final, 'zip')


bernoulli_graph

poi_graph

zip_graph



```
